# Generated by Django 5.0.1 on 2024-01-20 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_guruh_kurs_yonalish_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yonalish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.yonalish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kurs'),
        ),
    ]
