# Generated by Django 5.0.1 on 2024-01-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_kurs_alter_user_yonalish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kurs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lavozim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='yonalish',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
