# Generated by Django 5.0.1 on 2024-01-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_talaba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish', models.CharField(choices=[('MI', 'MI'), ('FA', 'FA')], default='MI', max_length=2)),
                ('kurs', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=2)),
                ('guruh', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='talaba',
            name='guruh',
        ),
        migrations.RemoveField(
            model_name='talaba',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='talaba',
            name='yonalish',
        ),
        migrations.AddField(
            model_name='talaba',
            name='fakultet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fakultet', to='users.fakultet'),
            preserve_default=False,
        ),
    ]
