# Generated by Django 5.0.1 on 2024-01-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0005_fakultet_guruh_kurs_yonalish_alter_davomat_fakultet_and_more'),
        ('users', '0011_alter_fakultet_yonalish_alter_user_yonalish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talaba',
            name='fakultet',
        ),
        migrations.DeleteModel(
            name='Fakultet',
        ),
        migrations.DeleteModel(
            name='Talaba',
        ),
    ]
