# Generated by Django 5.0.1 on 2024-01-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_talaba_fakultet_delete_fakultet_delete_talaba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lavozim',
            field=models.CharField(choices=[('admin', 'admin'), ('tyutr', 'tyutr')], default='tyutr', max_length=10),
        ),
    ]
