# Generated by Django 5.0.1 on 2024-01-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guruh',
        ),
        migrations.DeleteModel(
            name='Kurs',
        ),
        migrations.DeleteModel(
            name='Yonalish',
        ),
    ]
