# Generated by Django 5.0.1 on 2024-01-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0003_initial'),
        ('users', '0009_fakultet_remove_talaba_guruh_remove_talaba_kurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='davomat',
            name='amaliyot',
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='bor',
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='olinmadi',
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='talaba_id',
        ),
        migrations.RemoveField(
            model_name='davomat',
            name='yoq',
        ),
        migrations.AddField(
            model_name='davomat',
            name='fakultet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='davomat', to='users.fakultet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='davomat',
            name='kun',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Baza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attended', models.BooleanField(default=False)),
                ('amaliyot', models.BooleanField(default=False)),
                ('davomat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baza', to='davomat.davomat')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baza', to='users.talaba')),
            ],
            options={
                'unique_together': {('davomat', 'talaba')},
            },
        ),
    ]
