# Generated by Django 5.0.1 on 2024-01-23 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0004_remove_davomat_amaliyot_remove_davomat_bor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Matematika-informatika', 'Matematika-informatika'), ('Fizika-asteranomiya', 'Fizika-asteranomiya')], default='Matematika-informatika', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='davomat',
            name='fakultet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomat', to='davomat.fakultet'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='guruh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakultet', to='davomat.guruh'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakultet', to='davomat.kurs'),
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=270)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talaba', to='davomat.fakultet')),
            ],
        ),
        migrations.AlterField(
            model_name='baza',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baza', to='davomat.talaba'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakultet', to='davomat.yonalish'),
        ),
    ]
