# Generated by Django 5.0.1 on 2024-01-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0006_team_attendance_worker_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='position',
            new_name='sharif',
        ),
    ]
