# Generated by Django 5.0.1 on 2024-01-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0008_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='davomat',
            name='fakultet',
        ),
        migrations.RemoveField(
            model_name='fakultet',
            name='guruh',
        ),
        migrations.RemoveField(
            model_name='fakultet',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='fakultet',
            name='yonalish',
        ),
        migrations.RemoveField(
            model_name='talaba',
            name='fakultet',
        ),
        migrations.DeleteModel(
            name='Baza',
        ),
        migrations.DeleteModel(
            name='Davomat',
        ),
        migrations.DeleteModel(
            name='Fakultet',
        ),
        migrations.DeleteModel(
            name='Talaba',
        ),
    ]
