# Generated by Django 5.0.1 on 2024-01-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0009_remove_davomat_fakultet_remove_fakultet_guruh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='amaliyot',
            field=models.BooleanField(default=False),
        ),
    ]
