# Generated by Django 5.0.1 on 2024-01-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0010_mark_amaliyot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='sharif',
        ),
        migrations.AddField(
            model_name='worker',
            name='fish',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
