# Generated by Django 5.0.1 on 2024-01-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davomat', '0013_remove_worker_first_name_remove_worker_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='amaliyot',
        ),
    ]
